"""Production-facing public API for the ``aspose_pdf`` package."""

from ._version import __version__
from .annotations import (
    Annotation,
    AnnotationCollection,
    AnnotationFlags,
    AnnotationType,
    CircleAnnotation,
    FileAttachmentAnnotation,
    FreeTextAnnotation,
    HighlightAnnotation,
    InkAnnotation,
    LineAnnotation,
    LinkAnnotation,
    MarkupAnnotation,
    PolygonAnnotation,
    PolyLineAnnotation,
    PopupAnnotation,
    RedactAnnotation,
    SquareAnnotation,
    SquigglyAnnotation,
    StampAnnotation,
    StrikeOutAnnotation,
    TextAnnotation,
    UnderlineAnnotation,
    quad_from_rect,
)
from .attachments import AF_RELATIONSHIPS, FileSpecification
from .color import Color
from .destinations import NamedDestinationCollection
from .document import Document
from .exceptions import (
    FontEmbeddingException,
    PdfResourceLimitException,
    UnsupportedFeatureException,
)
from .facades import PdfExtractor, PdfFileEditor
from .font_registry import FontDescriptor
from .font_repository import (
    FileFontSource,
    FolderFontSource,
    FontRepository,
    FontSource,
    MemoryFontSource,
    SystemFontSource,
)
from .font_substitution import FontSubstitutionOptions
from .forms import (
    Field,
    FieldType,
    FieldWidget,
    Form,
    FormType,
    UnsignedContent,
    UnsignedContentAbsorber,
)
from .interactive import (
    Action,
    Destination,
    FitBDestination,
    FitBHDestination,
    FitBVDestination,
    FitDestination,
    FitHDestination,
    FitRDestination,
    FitVDestination,
    GoToAction,
    GoToRAction,
    JavaScriptAction,
    LaunchAction,
    NamedAction,
    ResetFormAction,
    SubmitFormAction,
    URIAction,
    XYZDestination,
)
from .load_limits import PdfLoadLimits
from .lowcode import (
    ByteArrayDataSource,
    DataSource,
    FileDataSource,
    MergeOptions,
    Merger,
    OperationResult,
    OptimizeOptions,
    Optimizer,
    PdfPlugin,
    Plugin,
    PluginOptions,
    ResultContainer,
    SplitOptions,
    Splitter,
    StreamDataSource,
    TextExtractor,
    TextExtractorOptions,
)
from .optimization import OptimizationOptions
from .page_labels import NumberingStyle, PageLabel, PageLabelCollection
from .page_size import PageSize
from .pages import Page, PageCollection
from .paths import GraphicsPath
from .pdfa import PdfAValidateOptions, PdfAValidationResult, PdfAValidator
from .pdfua import PdfUaValidateOptions, PdfUaValidationResult, PdfUaValidator
from .recipients import Recipient
from .signature import PdfSignature
from .stamps import (
    HorizontalAlignment,
    ImageStamp,
    PageNumberStamp,
    Stamp,
    TextStamp,
    VerticalAlignment,
)
from .tagged import StructureElement, TaggedContent
from .text_layout import TextLayoutOptions
from .validation import (
    CertificationLevel,
    RevocationStatus,
    TrustStatus,
    ValidationMethod,
    ValidationMode,
    ValidationOptions,
    ValidationResult,
    ValidationStatus,
)
from .viewer_preferences import (
    DuplexMode,
    PageBoundary,
    PageLayout,
    PageMode,
    PrintScaling,
    ReadingDirection,
    ViewerPreferences,
)
from .visualization import RasterizedPage
from .xmp import (
    NamespaceProvider,
    XmpArray,
    XmpField,
    XmpPacket,
    XmpProperty,
    XmpStruct,
)
from .xmp import (
    parse as parse_xmp,
)
from .xmp import (
    serialize as serialize_xmp,
)

__all__ = [
    "AF_RELATIONSHIPS",
    "Action",
    "Annotation",
    "AnnotationCollection",
    "AnnotationFlags",
    "AnnotationType",
    "ByteArrayDataSource",
    "CertificationLevel",
    "CircleAnnotation",
    "Color",
    "DataSource",
    "Destination",
    "Document",
    "DuplexMode",
    "Field",
    "FieldType",
    "FieldWidget",
    "FileAttachmentAnnotation",
    "FileDataSource",
    "FileFontSource",
    "FileSpecification",
    "FitBDestination",
    "FitBHDestination",
    "FitBVDestination",
    "FitDestination",
    "FitHDestination",
    "FitRDestination",
    "FitVDestination",
    "FolderFontSource",
    "FontDescriptor",
    "FontEmbeddingException",
    "FontRepository",
    "FontSource",
    "FontSubstitutionOptions",
    "Form",
    "FormType",
    "FreeTextAnnotation",
    "GoToAction",
    "GoToRAction",
    "GraphicsPath",
    "HighlightAnnotation",
    "HorizontalAlignment",
    "ImageStamp",
    "InkAnnotation",
    "JavaScriptAction",
    "LaunchAction",
    "LineAnnotation",
    "LinkAnnotation",
    "MarkupAnnotation",
    "MemoryFontSource",
    "MergeOptions",
    "Merger",
    "NamedAction",
    "NamedDestinationCollection",
    "NamespaceProvider",
    "NumberingStyle",
    "OperationResult",
    "OptimizationOptions",
    "OptimizeOptions",
    "Optimizer",
    "Page",
    "PageBoundary",
    "PageCollection",
    "PageLabel",
    "PageLabelCollection",
    "PageLayout",
    "PageMode",
    "PageNumberStamp",
    "PageSize",
    "PdfAValidateOptions",
    "PdfAValidationResult",
    "PdfAValidator",
    "PdfExtractor",
    "PdfFileEditor",
    "PdfLoadLimits",
    "PdfPlugin",
    "PdfResourceLimitException",
    "PdfSignature",
    "PdfUaValidateOptions",
    "PdfUaValidationResult",
    "PdfUaValidator",
    "Plugin",
    "PluginOptions",
    "PolyLineAnnotation",
    "PolygonAnnotation",
    "PopupAnnotation",
    "PrintScaling",
    "RasterizedPage",
    "ReadingDirection",
    "Recipient",
    "RedactAnnotation",
    "ResetFormAction",
    "ResultContainer",
    "RevocationStatus",
    "SplitOptions",
    "Splitter",
    "SquareAnnotation",
    "SquigglyAnnotation",
    "Stamp",
    "StampAnnotation",
    "StreamDataSource",
    "StrikeOutAnnotation",
    "StructureElement",
    "SubmitFormAction",
    "SystemFontSource",
    "TaggedContent",
    "TextAnnotation",
    "TextExtractor",
    "TextExtractorOptions",
    "TextLayoutOptions",
    "TextStamp",
    "TrustStatus",
    "URIAction",
    "UnderlineAnnotation",
    "UnsignedContent",
    "UnsignedContentAbsorber",
    "UnsupportedFeatureException",
    "ValidationMethod",
    "ValidationMode",
    "ValidationOptions",
    "ValidationResult",
    "ValidationStatus",
    "VerticalAlignment",
    "ViewerPreferences",
    "XYZDestination",
    "XmpArray",
    "XmpField",
    "XmpPacket",
    "XmpProperty",
    "XmpStruct",
    "__version__",
    "parse_xmp",
    "quad_from_rect",
    "serialize_xmp",
]
