from aspose_pdf.engine.simple_pdf import SimplePdf
from aspose_pdf.engine.cos import PdfDocument


def test_load_from_bytes_uses_cos_parser(tmp_path):
    # Create a minimal PDF (generated by PdfWriterV0 is fine as input)
    pdf = SimplePdf()
    pdf.pages = [(0, 0, 100, 100)]
    pdf.page_contents = [b""]
    data = pdf.to_bytes()

    # Load using the static method (which should now use CosParser)
    loaded = SimplePdf.from_bytes(data)

    # Verify internal backend is populated
    assert loaded._cos_doc is not None
    assert isinstance(loaded._cos_doc, PdfDocument)

    # Verify high-level properties are populated
    assert len(loaded.pages) == 1
    # SimplePdf defaults page size to 612x792 if not specified/parseable, or whatever original had
    # For now just check count.


def test_save_preserves_integrity(tmp_path):
    # Create a dummy PDF with a specific marker in COS if possible, or just check roundtrip
    # For now, minimal check:
    pdf = SimplePdf()
    pdf.pages = [(0, 0, 612, 792)]
    pdf.page_contents = [b"BT /F1 12 Tf (Hello World) Tj ET"]
    data = pdf.to_bytes()

    loaded = SimplePdf.from_bytes(data)
    assert loaded._cos_doc is not None

    # Save again
    output_path = tmp_path / "output.pdf"
    loaded.save(output_path)

    # Reload to verify
    reloaded = SimplePdf.from_file(str(output_path))
    assert len(reloaded.pages) == 1
    assert reloaded.get_text().strip() == "Hello World"


def test_modify_high_level_syncs_back(tmp_path):
    # Loading
    pdf = SimplePdf()
    pdf.pages = [(0, 0, 100, 100)]
    pdf.page_contents = [b""]
    data = pdf.to_bytes()

    loaded = SimplePdf.from_bytes(data)

    # Modify high-level
    loaded.pages.append((0, 0, 100, 100))
    loaded.page_contents.append(b"")

    # Save
    data2 = loaded.to_bytes()

    # Reload
    reloaded = SimplePdf.from_bytes(data2)
    assert len(reloaded.pages) == 2
