"""Tests for P0 bugfixes in aspose_pdf.

Generated by TestGeneratorAgent, then fixed for correctness.
"""

import ast
import inspect

import pytest

from aspose_pdf.document import Document
from aspose_pdf.engine.simple_pdf import (
    ImagePlacement,
    ImagePlacementAbsorber,
    SimplePdf,
)


# ---------------------------------------------------------------------------
# Fix 1 – SimplePdf.close() must delegate to dispose()
# ---------------------------------------------------------------------------


def test_close_calls_dispose():
    pdf = SimplePdf()
    pdf.close()
    assert pdf._disposed is True


def test_close_idempotent():
    pdf = SimplePdf()
    pdf.close()
    pdf.close()  # second call should not raise
    assert pdf._disposed is True


# ---------------------------------------------------------------------------
# Fix 2 – Orphaned dataclass fields removed from wrong classes
# ---------------------------------------------------------------------------


def test_image_placement_no_orphan_fields():
    """ImagePlacement and ImagePlacementAbsorber must NOT have cursor/map fields."""
    ip = ImagePlacement("test", 0, b"data")
    ipa = ImagePlacementAbsorber()
    for obj in (ip, ipa):
        assert not hasattr(obj, "_page_text_cursor")
        assert not hasattr(obj, "_page_image_map")


def test_simplepdf_has_cursor_fields():
    """SimplePdf instances SHOULD have _page_text_cursor attribute."""
    pdf = SimplePdf()
    assert hasattr(pdf, "_page_text_cursor")


# ---------------------------------------------------------------------------
# Fix 3 – Duplicate get_attach_names() removed
# ---------------------------------------------------------------------------


def test_get_attach_names_returns_names():
    pdf = SimplePdf()
    pdf.attachments = {"a.txt": b"data"}
    names = pdf.get_attach_names()
    assert names == ["a.txt"]


def test_get_attach_names_empty():
    pdf = SimplePdf()
    pdf.attachments = {}
    names = pdf.get_attach_names()
    assert names == []


def test_get_attach_names_no_duplicate_def():
    """get_attach_names must be defined exactly once in SimplePdf."""
    src_file = inspect.getsourcefile(SimplePdf)
    assert src_file is not None
    with open(src_file, "r", encoding="utf-8") as f:
        tree = ast.parse(f.read())
    class_node = None
    for node in tree.body:
        if isinstance(node, ast.ClassDef) and node.name == "SimplePdf":
            class_node = node
            break
    assert class_node is not None
    count = sum(
        1
        for n in class_node.body
        if isinstance(n, ast.FunctionDef) and n.name == "get_attach_names"
    )
    assert count == 1


# ---------------------------------------------------------------------------
# Fix 4 – Dead code in PageCollection.add()
# ---------------------------------------------------------------------------


def test_add_page_no_duplicates():
    """Adding pages twice must result in exactly two pages."""
    doc = Document()
    pages = doc.pages
    pages.add()
    pages.add()
    assert len(pages) == 2


def test_add_returns_page():
    """PageCollection.add() returns the added page."""
    doc = Document()
    pages = doc.pages
    page = pages.add()
    assert page is not None
    pages.add(page)
    assert len(pages) == 2


# ---------------------------------------------------------------------------
# Fix 5 – save_image() writes image bytes to disk
# ---------------------------------------------------------------------------


def test_save_image_writes_file(tmp_path):
    pdf = SimplePdf()
    pdf.images["img1"] = b"PNG_DATA"
    out_file = tmp_path / "out.png"
    pdf.save_image("img1", out_file)
    assert out_file.is_file()
    assert out_file.read_bytes() == b"PNG_DATA"


def test_save_image_missing_name_raises(tmp_path):
    pdf = SimplePdf()
    out_file = tmp_path / "out.png"
    with pytest.raises(KeyError):
        pdf.save_image("nonexistent", out_file)


def test_save_image_after_dispose_raises(tmp_path):
    pdf = SimplePdf()
    pdf.images["img1"] = b"PNG_DATA"
    pdf.dispose()
    out_file = tmp_path / "out.png"
    with pytest.raises(Exception):
        pdf.save_image("img1", out_file)
