"""Adobe glyph-name, encoding, and CFF-string tables.

The full Adobe Glyph List (4281 names), the four PDF predefined base encodings
(Standard/WinAnsi/MacRoman/MacExpert as code -> glyph name), the 391 predefined
CFF strings and the two predefined CFF charsets (Expert/ExpertSubset, as glyph
id -> name) are shipped as one bundled, integrity-checked blob under
``engine/data/agl/`` and generated by ``scripts/build_agl_data.py``. Name
resolution follows the Adobe "AGL Specification" algorithm, so a glyph name such
as ``aacute``, ``f_f_i``, ``Lcommaaccent``, or ``uni0041`` maps to its Unicode
string. The runtime never needs fontTools; only the blob is read.
"""

from __future__ import annotations

import hashlib
import json
import zlib
from functools import lru_cache
from importlib import resources

_BUNDLE_NAME = "agl/glyphlist.json.zlib"
_BUNDLE_SHA256 = "e0512727c35de809b8b2df71813d4e69ce318aabf4998b0b23049b1193f12a22"
_MAX_BUNDLE_BYTES = 1 << 20  # compressed guard (~27 KiB actual)
_MAX_BUNDLE_OUTPUT = 4 << 20  # decompressed guard (~110 KiB actual)
_MAX_NAME_LENGTH = 63  # bound the per-name algorithm work


@lru_cache(maxsize=1)
def _bundle() -> dict:
    compressed = (
        resources.files("aspose_pdf.engine.data").joinpath(_BUNDLE_NAME).read_bytes()
    )
    if len(compressed) > _MAX_BUNDLE_BYTES:
        raise RuntimeError("Bundled AGL data is unexpectedly large")
    if hashlib.sha256(compressed).hexdigest() != _BUNDLE_SHA256:
        raise RuntimeError("Bundled AGL data failed its integrity check")
    decompressor = zlib.decompressobj()
    raw = decompressor.decompress(compressed, _MAX_BUNDLE_OUTPUT + 1)
    if len(raw) > _MAX_BUNDLE_OUTPUT or decompressor.unconsumed_tail:
        raise RuntimeError("Bundled AGL data exceeds its output bound")
    raw += decompressor.flush()
    if len(raw) > _MAX_BUNDLE_OUTPUT:
        raise RuntimeError("Bundled AGL data exceeds its output bound")
    payload = json.loads(raw)
    if not isinstance(payload, dict) or payload.get("format") != 1:
        raise RuntimeError("Unsupported bundled AGL data format")
    return payload


@lru_cache(maxsize=1)
def _glyph_list() -> dict[str, str]:
    return {
        str(name): "".join(chr(int(scalar)) for scalar in scalars)
        for name, scalars in _bundle()["glyphs"].items()
    }


@lru_cache(maxsize=1)
def cff_standard_strings() -> tuple[str, ...]:
    """The 391 predefined CFF strings (SID -> name) for charset resolution."""
    return tuple(_bundle()["cff_standard_strings"])


_ENCODERS: dict[str, dict[int, int]] = {}


def _encoder_for(name: str) -> dict[int, int] | None:
    """``unicode scalar -> byte code`` for a predefined base encoding.

    Built by inverting the same table the reader resolves codes through, so a
    string this library writes and the same string read back agree by
    construction rather than by two tables happening to match. The lowest code
    wins where a scalar has more than one, which keeps the ASCII range as
    itself.
    """
    cached = _ENCODERS.get(name)
    if cached is not None:
        return cached
    table = base_encoding_table(name)
    if table is None:
        return None
    encoder: dict[int, int] = {}
    for code, glyph in enumerate(table):
        scalar = glyph_name_to_scalar(glyph) if glyph else None
        if scalar is not None:
            encoder.setdefault(scalar, code)
    _ENCODERS[name] = encoder
    return encoder


def glyph_name_to_scalar(name: str) -> int | None:
    """Resolve a glyph name to a *single* Unicode codepoint, or ``None``.

    A one-byte code stands for one glyph, and the tables that map codes to
    glyph names are read and written through this, so a name the AGL expands to
    a sequence (a ligature, say) has no place in either direction.
    """
    mapped = glyph_name_to_unicode(name)
    if mapped is None or len(mapped) != 1:
        return None
    return ord(mapped)


def encode_with_base_encoding(text: str, name: str) -> bytes | None:
    """Encode *text* into a simple font's one-byte codes, or ``None``.

    A string drawn with a simple font is a sequence of *codes in that font's
    encoding*, not text in some encoding of its own: byte 0xE9 is whatever
    glyph the font puts at 0xE9. Writing UTF-8 into one draws the glyphs those
    bytes happen to name -- two wrong letters for every accented one -- so a
    character the encoding has no code for has to stop the caller rather than
    be written as something else.

    ``None`` means some character has no code here, and names nothing about
    which: the caller reports the character itself, which is what the writer of
    the text needs to know.
    """
    encoder = _encoder_for(name)
    if encoder is None:
        return None
    out = bytearray()
    for character in text:
        code = encoder.get(ord(character))
        if code is None:
            return None
        out.append(code)
    return bytes(out)


def unencodable_characters(text: str, name: str) -> list[str]:
    """The characters of *text* that *name* has no code for, in order, once each."""
    encoder = _encoder_for(name) or {}
    seen: dict[str, None] = {}
    for character in text:
        if ord(character) not in encoder:
            seen.setdefault(character, None)
    return list(seen)


def base_encoding_table(name: str) -> tuple[str, ...] | None:
    """Return a predefined base encoding as a 256-tuple of code -> glyph name.

    Recognizes all four names PDF 32000-1 Table 114 allows -- ``StandardEncoding``,
    ``WinAnsiEncoding``, ``MacRomanEncoding`` and ``MacExpertEncoding`` (undefined
    codes are the empty string). Any other name is malformed rather than merely
    unsupported, and yields ``None`` so callers fall back rather than guess.

    ``MacRomanEncoding`` is the table PDF defines, which is a *subset* of the
    Mac OS Roman character set: 48 codes it leaves undefined belong to the
    font's own built-in encoding, not to this table. See
    :func:`mac_os_roman_supplement` for what a Mac-produced font is likely to
    put there when its built-in encoding says nothing either.
    """
    table = _bundle()["encodings"].get(name)
    return tuple(table) if table is not None else None


@lru_cache(maxsize=1)
def mac_os_roman_supplement() -> dict[int, str]:
    """Mac OS Roman names for codes PDF's MacRomanEncoding leaves undefined.

    A *last* resort, after ``/Differences``, the base encoding and the font's
    own built-in encoding. Imposing these names earlier would override the
    encoding the font actually carries -- which, in the subsetter, can keep the
    wrong glyph and erase the used one.
    """
    return {
        int(code): name
        for code, name in _bundle()["mac_os_roman_supplement"].items()
    }


@lru_cache(maxsize=2)
def cff_predefined_charset(index: int) -> tuple[str, ...] | None:
    """Return a predefined CFF charset as a glyph id -> name tuple, or ``None``.

    Charset offset 1 is Expert (166 glyphs) and 2 is ExpertSubset (87). Offset 0
    (ISOAdobe) is not here because it needs no table: glyph id *is* the SID.
    Unlike a charset stored in the font, these orderings are fixed by the CFF
    specification, so a font using one carries no glyph names of its own.
    """
    key = {1: "Expert", 2: "ExpertSubset"}.get(index)
    if key is None:
        return None
    table = _bundle()["cff_predefined_charsets"].get(key)
    return tuple(table) if table is not None else None


def _algorithmic_component(name: str) -> str | None:
    """Resolve a ``uniXXXX`` / ``uXXXX[X]`` component, or ``None``."""
    if name.startswith("uni"):
        hexpart = name[3:]
        if len(hexpart) < 4 or len(hexpart) % 4 != 0:
            return None
        scalars: list[int] = []
        for index in range(0, len(hexpart), 4):
            group = hexpart[index : index + 4]
            try:
                value = int(group, 16)
            except ValueError:
                return None
            if 0xD800 <= value <= 0xDFFF:  # surrogates are not valid uni-values
                return None
            scalars.append(value)
        return "".join(chr(value) for value in scalars)
    if name.startswith("u") and 5 <= len(name) <= 7:
        hexpart = name[1:]
        try:
            value = int(hexpart, 16)
        except ValueError:
            return None
        if 0xD800 <= value <= 0xDFFF or value > 0x10FFFF:
            return None
        return chr(value)
    return None


def glyph_name_to_unicode(name: str) -> str | None:
    """Map an Adobe glyph *name* to its Unicode string, or ``None``.

    Implements the Adobe AGL algorithm: drop everything from the first period,
    split the rest on underscores into components, and map each component
    through the Adobe Glyph List and then the algorithmic ``uniXXXX``/``uXXXX``
    forms. Any unresolved component makes the whole name unresolved, so callers
    never receive a guessed mapping.
    """
    if not isinstance(name, str) or not name or len(name) > _MAX_NAME_LENGTH:
        return None
    base = name.split(".", 1)[0]
    if not base:
        return None
    glyph_list = _glyph_list()
    parts: list[str] = []
    for component in base.split("_"):
        if not component:
            return None
        mapped = glyph_list.get(component)
        if mapped is None:
            mapped = _algorithmic_component(component)
        if mapped is None:
            return None
        parts.append(mapped)
    return "".join(parts)
