"""Adobe glyph-name, encoding, and CFF-string tables.

The full Adobe Glyph List (4281 names), the three PDF predefined base encodings
(Standard/WinAnsi/MacRoman as code -> glyph name), and the 391 predefined CFF
strings are shipped as one bundled, integrity-checked blob under
``engine/data/agl/`` and generated by ``scripts/build_agl_data.py``. Name
resolution follows the Adobe "AGL Specification" algorithm, so a glyph name such
as ``aacute``, ``f_f_i``, ``Lcommaaccent``, or ``uni0041`` maps to its Unicode
string. The runtime never needs fontTools; only the blob is read.
"""

from __future__ import annotations

import hashlib
import json
import zlib
from functools import lru_cache
from importlib import resources

_BUNDLE_NAME = "agl/glyphlist.json.zlib"
_BUNDLE_SHA256 = "334601d3644f58e36dd8ab5bf5ff289bdd5fd92b8f0017d35659573c958b7309"
_MAX_BUNDLE_BYTES = 1 << 20  # compressed guard (~27 KiB actual)
_MAX_BUNDLE_OUTPUT = 4 << 20  # decompressed guard (~110 KiB actual)
_MAX_NAME_LENGTH = 63  # bound the per-name algorithm work


@lru_cache(maxsize=1)
def _bundle() -> dict:
    compressed = (
        resources.files("aspose_pdf.engine.data").joinpath(_BUNDLE_NAME).read_bytes()
    )
    if len(compressed) > _MAX_BUNDLE_BYTES:
        raise RuntimeError("Bundled AGL data is unexpectedly large")
    if hashlib.sha256(compressed).hexdigest() != _BUNDLE_SHA256:
        raise RuntimeError("Bundled AGL data failed its integrity check")
    decompressor = zlib.decompressobj()
    raw = decompressor.decompress(compressed, _MAX_BUNDLE_OUTPUT + 1)
    if len(raw) > _MAX_BUNDLE_OUTPUT or decompressor.unconsumed_tail:
        raise RuntimeError("Bundled AGL data exceeds its output bound")
    raw += decompressor.flush()
    if len(raw) > _MAX_BUNDLE_OUTPUT:
        raise RuntimeError("Bundled AGL data exceeds its output bound")
    payload = json.loads(raw)
    if not isinstance(payload, dict) or payload.get("format") != 1:
        raise RuntimeError("Unsupported bundled AGL data format")
    return payload


@lru_cache(maxsize=1)
def _glyph_list() -> dict[str, str]:
    return {
        str(name): "".join(chr(int(scalar)) for scalar in scalars)
        for name, scalars in _bundle()["glyphs"].items()
    }


@lru_cache(maxsize=1)
def cff_standard_strings() -> tuple[str, ...]:
    """The 391 predefined CFF strings (SID -> name) for charset resolution."""
    return tuple(_bundle()["cff_standard_strings"])


def base_encoding_table(name: str) -> tuple[str, ...] | None:
    """Return a predefined base encoding as a 256-tuple of code -> glyph name.

    Recognizes ``StandardEncoding``, ``WinAnsiEncoding``, and ``MacRomanEncoding``
    (undefined codes are the empty string); ``None`` for any other name, so
    callers fall back rather than guess. Expert/MacExpert are not bundled.
    """
    table = _bundle()["encodings"].get(name)
    return tuple(table) if table is not None else None


def _algorithmic_component(name: str) -> str | None:
    """Resolve a ``uniXXXX`` / ``uXXXX[X]`` component, or ``None``."""
    if name.startswith("uni"):
        hexpart = name[3:]
        if len(hexpart) < 4 or len(hexpart) % 4 != 0:
            return None
        scalars: list[int] = []
        for index in range(0, len(hexpart), 4):
            group = hexpart[index : index + 4]
            try:
                value = int(group, 16)
            except ValueError:
                return None
            if 0xD800 <= value <= 0xDFFF:  # surrogates are not valid uni-values
                return None
            scalars.append(value)
        return "".join(chr(value) for value in scalars)
    if name.startswith("u") and 5 <= len(name) <= 7:
        hexpart = name[1:]
        try:
            value = int(hexpart, 16)
        except ValueError:
            return None
        if 0xD800 <= value <= 0xDFFF or value > 0x10FFFF:
            return None
        return chr(value)
    return None


def glyph_name_to_unicode(name: str) -> str | None:
    """Map an Adobe glyph *name* to its Unicode string, or ``None``.

    Implements the Adobe AGL algorithm: drop everything from the first period,
    split the rest on underscores into components, and map each component
    through the Adobe Glyph List and then the algorithmic ``uniXXXX``/``uXXXX``
    forms. Any unresolved component makes the whole name unresolved, so callers
    never receive a guessed mapping.
    """
    if not isinstance(name, str) or not name or len(name) > _MAX_NAME_LENGTH:
        return None
    base = name.split(".", 1)[0]
    if not base:
        return None
    glyph_list = _glyph_list()
    parts: list[str] = []
    for component in base.split("_"):
        if not component:
            return None
        mapped = glyph_list.get(component)
        if mapped is None:
            mapped = _algorithmic_component(component)
        if mapped is None:
            return None
        parts.append(mapped)
    return "".join(parts)
